#!/usr/bin/env python3

# You better ruuuun, ruuuun, ruuun, ruuuuuuun, ruun

import bluetooth

bd_addr = "00:22:05:00:31:4D"

port = 1

sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
sock.connect((bd_addr, port))

sock.send("testzor")

sock.close()
